name: Deploy
on:
  push:
    branches: [ develop,main ]
  pull_request:
    branches: [ develop,main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout 
        uses: actions/checkout@v2
      - name: Push imagen registry
        uses: azure/docker-login@v1
        with:
          login-server: registry.digitalocean.com
          username: ${{ secrets.REGISTRY_SECRET }}
          password: ${{ secrets.REGISTRY_SECRET }}
      - name: Docker Build (develop)
        if: github.ref == 'refs/heads/develop'
        run: |
            docker build . -t registry.digitalocean.com/bmlabs/neva/app-neva:dev-latest -f docker-build/Dockerfile.development
            docker push registry.digitalocean.com/bmlabs/neva/app-neva:dev-latest
      - name: Docker Build (main)
        if: github.ref == 'refs/heads/main'
        run: |
            docker build . -t registry.digitalocean.com/bmlabs/neva/app-neva:1.1 -f docker-build/Dockerfile.production
            docker push registry.digitalocean.com/bmlabs/neva/app-neva:1.1